name: app
repository: 123456789.dkr.ecr.us-east-1.amazonaws.com
image: app
tag: latest
containerPorts:
  http: 80
livenessProbe:
  path: /
  port: 80
readinessProbe:
  path: /
  port: 80
command: ["npm","start"]