name: app
repository: 123456789.dkr.ecr.us-east-1.amazonaws.com
image: app
tag: latest
containerPorts:
  http: 3000
livenessProbe:
  path: /
  port: 3000
readinessProbe:
  path: /
  port: 3000
command: ["npm","start"]