name: CD pipeline
on:
  push:
    branches:
      - master
      - develop
      - homolog
  workflow_dispatch:
jobs:
  deploy:
    runs-on: github-arc-runner-set
    env:
      DOCKER_IMAGE: "${{ vars.APPLICATION }}:${{ github.sha }}" # Use Git SHA as image tag
    steps:
    - name: Checkout sourcecode
      uses: actions/checkout@v4
    - name: Build image
      run: docker build -t ${{ env.DOCKER_IMAGE }} .
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Tag and push image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker tag ${{ env.DOCKER_IMAGE }} ${{ env.ECR_REGISTRY}}/${{ env.DOCKER_IMAGE }}
        docker push ${{ env.ECR_REGISTRY}}/${{ env.DOCKER_IMAGE }}
    #- run: docker buildx create --name remote --driver remote tcp://buildkitd.buildkitd:1234
    #- run: docker buildx build --builder=remote -t hello:latest .
    #- run: docker buildx build --builder=remote -t test --load .
