name: CD pipeline
on:
  push:
    branches:
      - master
      - develop
      - homolog
  workflow_dispatch:
jobs:
  build:
    runs-on: github-arc-runner-set
    env:
      DOCKER_IMAGE: "${{ var.APPLICATION }}:${{ github.sha }}" # Use Git SHA as image tag
    steps:
    - name: Checkout sourcecode
      uses: actions/checkout@v4
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Setup buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker build/push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: "${{ steps.login-ecr.outputs.registry }}/${{ env.DOCKER_IMAGE }}"
    #- run: docker buildx create --name remote --driver remote tcp://buildkitd.buildkitd:1234
    #- run: docker buildx build --builder=remote -t hello:latest .
    #- run: docker buildx build --builder=remote -t test --load .
