name: CD pipeline
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - master
      - develop
      - homolog
  workflow_dispatch:
jobs:
  deploy:
    runs-on: github-arc-runner-set
    env:
      DOCKER_IMAGE: "${{ vars.APPLICATION }}:${{ github.sha }}" # Use Git SHA as image tag
    steps:
    - name: Checkout sourcecode
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::127923327338:role/github-actions-runner-role
        aws-region: us-east-1
        audience: sts.amazonaws.com
#    - name: Configure AWS Credentials
#      uses: aws-actions/configure-aws-credentials@v4
#      with:
#        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
#    - name: Build image
#      run: docker build -t ${{ env.DOCKER_IMAGE }} .
#    - name: Tag and push image
#      env:
#        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#      run: |
#        docker tag ${{ env.DOCKER_IMAGE }} ${{ env.ECR_REGISTRY}}/${{ env.DOCKER_IMAGE }}
#        docker push ${{ env.ECR_REGISTRY}}/${{ env.DOCKER_IMAGE }}
    - name: aws cli
      uses: docker://amazon/aws-cli:2.30.6
      with:
        args: aws sts get-caller-identity
    - name: Helm install
      uses: ./.github/actions/kubectl-helm
      with:
        run: |
          aws eks update-kubeconfig --region us-east-1 --name eks-infra --kubeconfig /github/workspace/kubeconfig
          cat /github/workspace/kubeconfig
          export KUBECONFIG='/github/workspace/kubeconfig'
          kubectl create namespace production
          #helm upgrade --install ${{ vars.APPLICATION }} --namespace production --set tag=${{ github.sha }} helm-chart/app/

    #- run: docker buildx create --name remote --driver remote tcp://buildkitd.buildkitd:1234
    #- run: docker buildx build --builder=remote -t hello:latest .
    #- run: docker buildx build --builder=remote -t test --load .
