name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: github-arc-runner-set
    steps:
    - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
    #- run: docker build . --file Dockerfile --tag hello:latest
    - run: docker buildx create --name remote --driver remote tcp://buildkitd.buildkitd:1234
