name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: github-arc-runner-set
    steps:
    - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
    - name: Set up containerd
      uses: crazy-max/ghaction-setup-containerd@v3
    - uses: actions/checkout@v4
    #- run: docker buildx create --name remote --driver remote tcp://buildkitd.buildkitd:1234
    #- run: docker buildx build --builder=remote -t hello:latest .
    #- run: docker buildx build --builder=remote -t test --load .
    #services:
    #  redis:
    #    image: redis:latest
